### ISSUE TITLE
Built-in FindTBB.cmake fails to find OpenTBB-2021.3.0

### ISSUE THREAD

**Issue by yurivict** [COMBINE-lab/pufferfish#26]
It finds TBB_VERSION as "."

Version: 1.5.2
OS: FreeBSD 13

**Comment by fataltes** [comment]
Thank you @yurivict ,

I'll take a look at FindTBB and get back to you.

**Comment by rob-p** [comment]
Hi @yurivict and @fataltes,

  This turned out to be a big issue because IntelTBB became oneTBB and they changed some fundamental stuff in a backward incompatible way.  The current develop branch of pufferfish must be built with a TBB prior to version 2021.1.  However, there is now a `onetbb` branch that will be merged to develop soon that should fix the build to work with new versions of oneTBB.

--Rob

**Comment by rob-p** [comment]
This is now addressed in the `develop` branch (which we have changed to the default branch).
